name: CI

on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:

            -   name: checkout code
                uses: actions/checkout@v3

            -   name: build container
                run: docker build -t phpxmlrpc-debugger-local .

            # @todo start the container, check that the debugger is working with a few simple http requests
